name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu de mon dépôt git
      - run: ls -l # Liste les fichier du répertoire courant
      - run: |
          sudo apt-get update
          sudo apt-get install --yes cowsay # si tu me poses des question c'est oui
      - run: cat README.md. | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt
      - uses: actions/setup-node@v3 # Permet définir une version de node sur laquelle le projet va tourner
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run lint
    