name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu de mon dépôt git
      - run: ls -l # Liste les fichier du répertoire courant
      - run: |
          sudo apt-get update
          sudo apt-get install --yes cowsay # si tu me poses des question c'est oui
      - run: cat README.md. | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt